// Builds the bundled coin/market logo set into public/logos and a manifest the app imports.
//   crypto  : @web3icons/core (MIT, "background" variant) then cryptocurrency-icons (CC0)
//   stocks  : simple-icons (CC0) glyph on the brand colour
//   other   : hand-made SVGs in custom-logos.mjs (commodities, indices, FX)
// Anything not bundled is loaded from Hyperliquid's own coin CDN at runtime.
import { mkdirSync, readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ALIASES, CUSTOM_LOGOS, STOCK_SLUGS } from "./custom-logos.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const app = path.resolve(here, "..");
const outDir = path.join(app, "public/logos");
const genDir = path.join(app, "src/generated");
// node_modules symlinks (pnpm) — resolved directly since some packages hide package.json behind "exports".
const pkgDir = (name) => path.join(app, "node_modules", name);

mkdirSync(outDir, { recursive: true });
mkdirSync(genDir, { recursive: true });

const logos = new Map(); // SYMBOL -> svg
const put = (sym, svg) => {
  if (svg && !logos.has(sym)) logos.set(sym, svg);
};

// 1. Custom (wins over packs).
for (const [sym, svg] of Object.entries(CUSTOM_LOGOS)) put(sym, svg);

// 2. Stocks via simple-icons.
const si = pkgDir("simple-icons");
const siData = JSON.parse(readFileSync(path.join(si, "data/simple-icons.json"), "utf8"));
const siList = Array.isArray(siData) ? siData : siData.icons;
const lum = (hex) => {
  const n = parseInt(hex, 16);
  return (0.299 * ((n >> 16) & 255) + 0.587 * ((n >> 8) & 255) + 0.114 * (n & 255)) / 255;
};
for (const [ticker, slug] of Object.entries(STOCK_SLUGS)) {
  const file = path.join(si, "icons", `${slug}.svg`);
  if (!existsSync(file)) continue;
  const meta = siList.find((i) => i.slug === slug);
  const d = /d="([^"]+)"/.exec(readFileSync(file, "utf8"))?.[1];
  if (!d) continue;
  let bg = `#${meta?.hex ?? "1F2326"}`;
  let fg = "#fff";
  const l = lum(bg.slice(1));
  if (l < 0.08) bg = "#1F2326"; // near-black brands: dark grey disc
  if (l > 0.72) fg = "#111"; // very light brands: dark glyph
  put(ticker, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><circle cx="16" cy="16" r="16" fill="${bg}"/><g transform="translate(8 8) scale(.6667)"><path d="${d}" fill="${fg}"/></g></svg>`);
}

// 3. Crypto via web3icons (background variant = glyph on brand colour), then cryptocurrency-icons.
const w3 = path.join(pkgDir("@web3icons/core"), "dist/svgs/tokens/background");
for (const f of readdirSync(w3)) {
  if (!f.endsWith(".svg.js")) continue;
  const sym = f.slice(0, -7).toUpperCase();
  const src = readFileSync(path.join(w3, f), "utf8");
  const m = /'(<svg[\s\S]*?<\/svg>)(?:\\n)?'/.exec(src);
  if (!m) continue;
  // namespace clip-path ids per file so nothing collides if inlined later
  put(sym, m[1].replace(/\\n/g, "").replace(/\\'/g, "'").replace(/class="web3icons"/, "").replace(/id="([^"]+)"/g, `id="${sym}-$1"`).replace(/url\(#([^)]+)\)/g, `url(#${sym}-$1)`));
}
const cc = path.join(pkgDir("cryptocurrency-icons"), "svg/color");
for (const f of readdirSync(cc)) {
  if (f.endsWith(".svg")) put(f.slice(0, -4).toUpperCase(), readFileSync(path.join(cc, f), "utf8"));
}

// Aliases point at an existing logo.
for (const [from, to] of Object.entries(ALIASES)) if (!logos.has(from) && logos.has(to)) logos.set(from, logos.get(to));

for (const [sym, svg] of logos) writeFileSync(path.join(outDir, `${encodeURIComponent(sym)}.svg`), svg);
const names = [...logos.keys()].sort();
writeFileSync(
  path.join(genDir, "logos.ts"),
  `// Generated by scripts/build-logos.mjs. Do not edit.\nexport const BUNDLED_LOGOS: ReadonlySet<string> = new Set(${JSON.stringify(names)});\n`,
);
console.log(`logos: ${names.length} bundled (${Object.keys(CUSTOM_LOGOS).length} custom, stocks via simple-icons, crypto via web3icons + cryptocurrency-icons)`);
